frontend/Sample/Controllers/ReceiveController.cs
using System.Security.Authentication;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Sample.Models;
using Sample.Service;

namespace Sample.Controllers
{
    public class ReceiveController : Controller
    {
        private readonly INotyfService _notyf;
        private readonly HttpClient _httpClient = new();
        private readonly ReceiveService _receiveService;
        private readonly UserService _userService;

        public ReceiveController(INotyfService notyf, ReceiveService receiveService, UserService userService)
        {
            _notyf = notyf;
            _receiveService = receiveService;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                return View(await _receiveService.GetAll(HttpContext));
            }
            catch (AuthenticationException)
            {
                return RedirectToAction("Login", "Auth");
            }
            catch (HttpRequestException)
            {
                return RedirectToAction("Login", "Auth");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Login", "Auth");
            }
        }

        public async Task<IActionResult> Create()
        {
            ReceiveDto receiveDto = new();
            receiveDto.Users = await _userService.GetAll(HttpContext);
            return View(receiveDto);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ReceiveDto receiveDto)
        {
            await _receiveService.Create(receiveDto, HttpContext, _notyf);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(long id)
        {
            var receive = await _receiveService.GetById(id, HttpContext);
            if (receive == null)
            {
                return NotFound();
            }
            return View(receive);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ReceiveDto receiveDto)
        {
            await _receiveService.Edit(receiveDto, HttpContext, _notyf);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(long id)
        {
            var receive = await _receiveService.GetById(id, HttpContext);
            if (receive == null)
            {
                return NotFound();
            }

            await _receiveService.DeleteById(id, HttpContext, _notyf);

            return RedirectToAction("Index");
        }
    }
}

frontend/Sample/Controllers/SendController.cs
using System.Security.Authentication;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Sample.Models;
using Sample.Service;

namespace Sample.Controllers
{
    public class SendController : Controller
    {
        private readonly INotyfService _notyf;
        private readonly HttpClient httpClient = new();
        private readonly ReceiveService _receiveService;
        private readonly UserService _userService;
        private readonly SendService _sendService;

        public SendController(INotyfService notyf, ReceiveService receiveService, UserService userService, SendService sendService)
        {
            _notyf = notyf;
            _receiveService = receiveService;
            _userService = userService;
            _sendService = sendService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                return View(await _sendService.GetAll(HttpContext));
            }
            catch (AuthenticationException)
            {
                return RedirectToAction("Login", "Auth");
            }
            catch (HttpRequestException)
            {
                return RedirectToAction("Login", "Auth");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Login", "Auth");
            }
        }

        public async Task<IActionResult> Create()
        {
            SendDto sendDto = new()
            {
                Users = await _userService.GetAll(HttpContext),
                Receives = await _receiveService.GetAll(HttpContext)
            };
            return View(sendDto);
        }

        [HttpPost]
        public async Task<IActionResult> Create(SendDto sendDto)
        {
            await _sendService.Create(sendDto, HttpContext, _notyf);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(long id)
        {
            var send = await _sendService.GetById(id, HttpContext);
            if (send == null)
            {
                return NotFound();
            }
            return View(send);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SendDto sendDto)
        {
            await _sendService.Edit(sendDto, HttpContext, _notyf);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(long id)
        {
            var send = await _sendService.GetById(id, HttpContext);
            if (send == null)
            {
                return NotFound();
            }

            await _sendService.DeleteById(id, HttpContext, _notyf);

            return RedirectToAction("Index");
        }
    }
}

frontend/Sample/Controllers/UserController.cs
using System.Security.Authentication;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Sample.Models;
using Sample.Service;

namespace Sample.Controllers
{
    public class UserController : Controller
    {
        private readonly INotyfService _notyf;
        private readonly HttpClient _httpClient = new();
        private readonly UserService _userService;

        public UserController(INotyfService notyf, UserService userService)
        {
            _notyf = notyf;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                return View(await _userService.GetAll(HttpContext));
            }
            catch (AuthenticationException)
            {
                return RedirectToAction("Login", "Auth");
            }
            catch (HttpRequestException)
            {
                return RedirectToAction("Login", "Auth");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Login", "Auth");
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserDto userDto)
        {
            await _userService.Create(userDto, HttpContext, _notyf);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(long id)
        {
            var user = await _userService.GetById(id, HttpContext);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserDto userDto)
        {
            await _userService.Edit(userDto, HttpContext, _notyf);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(long id)
        {
            var user = await _userService.GetById(id, HttpContext);
            if (user == null)
            {
                return NotFound();
            }

            await _userService.DeleteById(id, HttpContext, _notyf);
            return RedirectToAction("Index");
        }
    }
}

frontend/Sample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sample.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SampleDonations</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Auth" asp-action="Login">Entrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">Usuário</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Receive" asp-action="Index">Recebimento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Send" asp-action="Index">Envios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="modal fade" id="form-modal" tabindex="-1" aria-labelledby="form-modalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="form-modalLabel"></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>

    <footer class="footer bg-light text-muted border-top">
        <div class="container text-center">
            &copy; 2024 - Sample - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("Notyf")
</body>
</html>

frontend/Sample/Views/Shared/_LayoutModal.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SampleDonations</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SampleDonations.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>